from __future__ import annotations

import argparse
import sys
from pathlib import Path


# Allow running this script directly from the repository root, e.g.
# python scripts/run_training.py ...
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from model_learning import run_experiment, summarize_auc_results  # noqa: E402
from model_learning.experiment import (  # noqa: E402
    DEFAULT_CPU_MODELS,
    DEFAULT_FEATURE_SETS,
    DEFAULT_GPU_MODELS,
    DEFAULT_PCA_MODES,
)
from model_learning.models import MODEL_REGISTRY  # noqa: E402


DEEP_LEARNING_MODELS = {"ANN", "RNN"}
DEFAULT_MODELS = tuple(DEFAULT_CPU_MODELS) + tuple(DEFAULT_GPU_MODELS)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Run MRSi-AI model training and evaluation."
    )

    parser.add_argument(
        "--input-csv",
        required=True,
        type=Path,
        help="Path to the preprocessed CSV file generated by run_preprocessing.py.",
    )
    parser.add_argument(
        "--output-dir",
        default=Path("result"),
        type=Path,
        help="Directory where model outputs, plots, and JSON results will be saved.",
    )
    parser.add_argument(
        "--result-json",
        default=None,
        type=Path,
        help=(
            "Optional path for the nested result JSON file. "
            "If omitted, <output-dir>/result.json is used."
        ),
    )
    parser.add_argument(
        "--summary-csv",
        default=None,
        type=Path,
        help=(
            "Optional path for an AUC summary CSV file. "
            "If omitted, <output-dir>/auc_summary.csv is used."
        ),
    )
    parser.add_argument(
        "--data-type",
        default="diag",
        help=(
            "Value in the data_type column to use for training, such as 'diag' or 'drug'. "
            "Use --no-data-type-filter to use all rows without filtering."
        ),
    )
    parser.add_argument(
        "--no-data-type-filter",
        action="store_true",
        help="Do not filter rows by the data_type column before training.",
    )
    parser.add_argument(
        "--drop-contains",
        nargs="*",
        default=["ins", "glu", "hba1c"],
        help=(
            "Column-name substrings to remove before model training. "
            "Default: ins glu hba1c. Pass no values after the flag to disable this drop."
        ),
    )
    parser.add_argument(
        "--feature-sets",
        nargs="+",
        default=list(DEFAULT_FEATURE_SETS),
        choices=list(DEFAULT_FEATURE_SETS),
        help=f"Feature sets to evaluate. Default: {' '.join(DEFAULT_FEATURE_SETS)}.",
    )
    parser.add_argument(
        "--pca-modes",
        nargs="+",
        default=list(DEFAULT_PCA_MODES),
        choices=list(DEFAULT_PCA_MODES),
        help=f"PCA modes to evaluate. Default: {' '.join(DEFAULT_PCA_MODES)}.",
    )
    parser.add_argument(
        "--models",
        nargs="+",
        default=list(DEFAULT_MODELS),
        choices=list(MODEL_REGISTRY),
        help=(
            "Models to run. ANN/RNN are executed sequentially in the main process; "
            "the remaining models are executed as CPU models. "
            f"Default: {' '.join(DEFAULT_MODELS)}."
        ),
    )
    parser.add_argument(
        "--sampling",
        default="over",
        choices=["none", "over"],
        help="Sampling strategy passed to data_split. Default: over.",
    )
    parser.add_argument(
        "--n-jobs",
        default=3,
        type=int,
        help="Number of parallel workers for CPU models. Default: 3.",
    )
    parser.add_argument(
        "--random-state",
        default=123,
        type=int,
        help="Random seed used by splitting and model training. Default: 123.",
    )
    parser.add_argument(
        "--no-plots",
        action="store_true",
        help="Disable saving ROC curves and feature-importance plots.",
    )
    parser.add_argument(
        "--no-shap",
        action="store_true",
        help="Disable SHAP analysis for tree boosting models.",
    )
    parser.add_argument(
        "--save-xgb-trees",
        action="store_true",
        help=(
            "Save XGBoost tree visualizations. This can be slow and requires "
            "both the Python graphviz package and the system Graphviz binary."
        ),
    )

    return parser.parse_args()


def split_model_groups(model_names: list[str]) -> tuple[list[str], list[str]]:
    """Split requested models into CPU-parallel and sequential DL groups."""
    cpu_models = [name for name in model_names if name not in DEEP_LEARNING_MODELS]
    gpu_models = [name for name in model_names if name in DEEP_LEARNING_MODELS]
    return cpu_models, gpu_models


def main() -> None:
    """Run model training from command-line arguments."""
    args = parse_args()

    data_type = None if args.no_data_type_filter else args.data_type
    cpu_models, gpu_models = split_model_groups(args.models)

    result = run_experiment(
        input_csv=args.input_csv,
        output_dir=args.output_dir,
        result_json=args.result_json,
        data_type=data_type,
        drop_contains=tuple(args.drop_contains),
        feature_sets=tuple(args.feature_sets),
        pca_modes=tuple(args.pca_modes),
        cpu_models=tuple(cpu_models),
        gpu_models=tuple(gpu_models),
        sampling_method=args.sampling,
        n_jobs=args.n_jobs,
        random_state=args.random_state,
        make_plots=not args.no_plots,
        make_shap=not args.no_shap,
        save_xgb_trees=args.save_xgb_trees,
    )

    summary_df = summarize_auc_results(result)
    summary_csv = args.summary_csv or args.output_dir / "auc_summary.csv"
    summary_csv.parent.mkdir(parents=True, exist_ok=True)
    summary_df.to_csv(summary_csv, index=False)

    result_json = args.result_json or args.output_dir / "result.json"

    print("Training completed.")
    print(f"Result JSON: {result_json}")
    print(f"AUC summary CSV: {summary_csv}")

    if not summary_df.empty:
        best_row = summary_df.iloc[0]
        print(
            "Best validation AUC: "
            f"{best_row['auc_validation']} "
            f"({best_row['feature_set']} / {best_row['pca_mode']} / {best_row['model']})"
        )


if __name__ == "__main__":
    main()
